apiVersion: mcp.mcp.dev/v1alpha1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: smooth-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample
spec:
  # TODO(user): Add fields here
